/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Drakonas15 (https://sketchfab.com/Drakonas15)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dinosaur-walking-9b3dc24306ee4d85834a84a34a247586
title: dinosaur walking
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Dino({}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/dino.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group scale={0.5} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="_0">
          <mesh
            name="mesh_0"
            geometry={nodes.mesh_0.geometry}
            material={materials.mesh_0}
            morphTargetDictionary={nodes.mesh_0.morphTargetDictionary}
            morphTargetInfluences={nodes.mesh_0.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/dino.gltf");
